### ISSUE TITLE
Window.close() not working

### ISSUE THREAD

**Issue by nguyentho98** [arye321/nextauth-google-popup-login#1]
Your code works well but I'm not able to close the new window using window.close(). It doesn't close, on Chrome at least.

How can I fix it? I've tried some different ways but without success.

Thanks!

**Comment by sketchmonk-dev** [comment]
Same for me as well

**Comment by arye321** [comment]
Sorry, works fine on my Chrome

**Comment by nguyentho98** [comment]
Sad!

**Comment by jsjoeio** [comment]
Did anyone find a workaround?

**Comment by jsjoeio** [comment]
I don't know what I did differently lol but now it's working for me!

Demo:

https://user-images.githubusercontent.com/3806031/226216487-7326ec10-9a18-4c6e-94c8-48a7098ca425.mp4

Thank you for making this!

**Comment by arye321** [comment]
> I don't know what I did differently lol but now it's working for me!

awesome!
