### ISSUE TITLE
Try signing in with a different account

### ISSUE THREAD

**Issue by vaneSusu** [arye321/nextauth-google-popup-login#4]
I run the project, just changed some Google-related information, and encountered the error "Try signing in with a different account."
I don't know why this happened. Do you know what might be the cause?

**Comment by vaneSusu** [comment]
![Uploading WX20240111-235532@2x.png…]()

**Comment by vaneSusu** [comment]
![WX20240111-235532@2x](https://github.com/arye321/nextauth-google-popup-login/assets/20024214/27a4cf17-5e8c-4c9b-8a78-5421426a5f55)

**Comment by arye321** [comment]
No idea, I think its a Google thing. but all my accounts work
